#! /bin/bash

cd ./download-server-project
version=$(cat version.txt)

dotnet add package Microsoft.CodeAnalysis.LanguageServer.neutral -v $version

cd out/microsoft.codeanalysis.languageserver.neutral/$version/content/LanguageServer/neutral
zip -r language-server.zip ./*

mv language-server.zip ../../../../../../..
cd ../../../../../../

rm -rf out

cd ..
