#! /bin/bash

version=$(cat src/server_version.rs | sed -n 's/.*"\(.*\)".*/\1/p')
cd ./download-server-project

dotnet add package Microsoft.CodeAnalysis.LanguageServer.neutral -v $version

cd out/microsoft.codeanalysis.languageserver.neutral/$version/content/LanguageServer/neutral
zip -r language-server.zip ./*

mv language-server.zip ../../../../../../..
cd ../../../../../../

rm -rf out

cd ..
